[workspace]
members = [
    "d01t1",
    "d01t2",
    "d02t1",
    "d02t2",
    "d03t1",
    "d03t2",
    "d04t1",
    "d04t2",
    "d05t1",
    "d05t2",
    "d06t1",
    "d06t2",
    "d07t1",
    "d07t2",
    "d08t1",
    "d08t2",
    "d09t1",
    "d09t2",
    "d10t1",
    "d10t2",
]
